site_name: QTradeX Docs
site_url: https://qtradex.litepresence.com/
docs_dir: docs
site_dir: gh-docs
use_directory_urls: true

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Writing a Bot: writing-a-bot.md
  - Optimization: optimization.md
  - Live Trading: live-trading.md
  - API Reference:
      - api/data.md
      - api/signals.md
      - api/basebot.md
      - api/optimizers.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidKid-deluxe/QTradeX-Algo-Trading-SDK
    - icon: fontawesome/brands/telegram
      link: https://t.me/qtradex_sdk

copyright: Copyright &copy; 2026 QTradeX — WTFPL
